### ISSUE TITLE
backend todo

### ISSUE THREAD

**Issue by tr-vs** [tr-vs/realist#121]
- [x] revamp user auth method
- [x] fix bug for new users whenever they connect their spotify
- [ ] when users' jwt tokens expire, they should be signed out
- [x] passage email formatting
- [ ] return top artists/songs id
- [x] create playlist
